# The main configuration file for the framework.

# Include the database properties.
include: ["database.yaml"]

# Tools used by the framework.
tool:
  compare_it:
    executable: "wincmp3.exe"
  7z:
    executable: "7z.exe"

logging:
  console:
    level: "DEBUG"
    pattern : "[%d] %-5l -- %c (%x) : %m\\n"
    date_pattern: "%d-%b-%Y %H:%M:%S.%L %z"
  file:
    pattern: "[%d] %-5l -- %c (%x) : %m\\n"
    date_pattern: "%d-%b-%Y %H:%M:%S.%L %z"

data:
  directory: "${root_directory}/Data"

temp:
  directory: "${data.directory}/Temp"

# The directory that contains all result files.
results:
  archive: "${data.directory}/Archive/Results"

# Run configurations.
run:
  name: "${run.config_name}_${run.start_date_time}"
  type: "default"
  working:
    directory: "${temp.directory}/${run.name}"
  analysis:
    directory: "${run.working.directory}/Analysis"
  result:
    directory: "${run.working.directory}/Results"
    zip_file_name: "${run.name}.zip"
  trigger:
    user:
    official_users: ["Schedule Trigger", "Subversion"]

# Mode properties.
mode:
  rake:
    description: "Executes tasks in separate processes using Rake (no support for parallel execution)."
  execute:
    description: "Executes tasks in separate processes using Ruby (full support for parallel execution)"
  # Administrative modes.
  console:
    description: "An interactive console for running administrative tasks."
  janitor:
    description: "Performs general clean-up tasks."

# Database properties.
database:
  results_database:
    singleton: true

result_data:
  run_result_data:
    empty:
  result_archive:
    singleton: true

# Task properties.
task:
  pid: "${run.pid}"
  results:
    zip_file_name: "${task.name}.zip"

  finaliser:
    depends_on: []
  analyser:
    depends_on: ["finaliser"]
